services:
  backend:
    image: node:24-slim
    user: "1001:1001"
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - path: .env
        required: false
    environment:
      PORT: 3000
      npm_config_cache: /tmp/.npm
    ports:
      - "3000:3000"
    command: node --watch src/server.js
